"""Registry of spoken languages Yachachiq can hear (ASR), speak (TTS) and
translate, with honest per-engine availability (CONTRACTS.md §6).

The data file `data/languages.json` is generated by
`tools/voice_build_languages.py` from the engines' own language lists
(Whisper, Meta Omnilingual ASR, MMS-TTS, Piper, NLLB-200, MADLAD-400) plus
ISO 639-3 / Glottolog / CLDR names. Nothing here needs a model or internet.

    from yq.common import languages
    languages.get("quy_Latn").name_es        -> "Quechua ayacuchano (chanka)"
    languages.get("es").code                 -> "spa_Latn"   (ISO 639-1/3, BCP-47, Whisper codes work)
    languages.ui_list("asr")[:3]             -> Spanish, Quechua (Chanka), Quechua (Cusco)...
    languages.search("aimara")               -> [Language(ayr_Latn ...), ...]

`popular` is a display rank: 1 = first in the picker (Spanish, then the
Peruvian languages, then the world's most spoken); 0 = not ranked (these come
after the ranked ones, alphabetically by Spanish name).
"""
from __future__ import annotations

import builtins
import json
import re
import threading
import unicodedata
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Optional

DATA_FILE = Path(__file__).resolve().parent / "data" / "languages.json"
FEATURES = ("asr", "tts", "translate", "any", "all")
# Macrolanguage codes -> the variety we use by default (NLLB's choice).
MACRO_DEFAULT = {"qu": "quy_Latn", "que": "quy_Latn", "ay": "ayr_Latn", "aym": "ayr_Latn",
                 "zho": "cmn_Hans", "ara": "arb_Arab", "fas": "pes_Arab", "msa": "zsm_Latn",
                 "swa": "swh_Latn", "est": "ekk_Latn", "lav": "lvs_Latn", "uzb": "uzn_Latn",
                 "aze": "azj_Latn", "nor": "nob_Latn", "sqi": "als_Latn", "mon": "khk_Cyrl",
                 "pus": "pbt_Arab", "nep": "npi_Deva", "yid": "ydd_Hebr", "grn": "grn_Latn"}


@dataclass
class Language:
    code: str                       # canonical FLORES-200 style, e.g. "quy_Latn"
    iso639_3: str
    name_native: str
    name_es: str
    name_en: str
    region: str                     # "Perú" for Peruvian languages, else a macro-area in Spanish
    asr: list = field(default_factory=list)       # engines that can transcribe it: "whisper", "omniasr"
    tts: list = field(default_factory=list)       # engines that can speak it: "piper", "mms"
    translate: bool = False                       # NLLB-200 or MADLAD-400 can translate it
    whisper_code: str = ""
    popular: int = 0
    # extra (not in the contract, safe to ignore)
    iso639_1: str = ""
    script: str = ""
    countries: list = field(default_factory=list)
    whisper_strong: bool = False    # Whisper large-v3 FLEURS error <= 15 %
    peru: bool = False
    aliases: list = field(default_factory=list)
    engines: dict = field(default_factory=dict)   # per-engine codes: whisper, omniasr, nllb, madlad, mms_tts, mms_lid, piper
    quality: dict = field(default_factory=dict)   # published numbers: whisper_large_v3_fleurs_wer, omniasr_7b_cer ...

    def to_dict(self) -> dict:
        return asdict(self)

    def has(self, feature: str) -> bool:
        if feature == "asr":
            return bool(self.asr)
        if feature == "tts":
            return bool(self.tts)
        if feature == "translate":
            return bool(self.translate)
        if feature == "all":
            return bool(self.asr and self.tts and self.translate)
        return bool(self.asr or self.tts or self.translate)


_lock = threading.Lock()
_langs: Optional[list] = None
_by_code: dict = {}
_alias: dict = {}          # lower-case alternative code -> canonical code
_meta: dict = {}


def normalize(text: str) -> str:
    """Lower case, no accents (keeps ñ distinct from n is NOT needed for search)."""
    text = unicodedata.normalize("NFKD", str(text or "").lower())
    text = "".join(c for c in text if not unicodedata.combining(c))
    return re.sub(r"\s+", " ", text).strip()


def _load() -> None:
    global _langs, _meta
    with _lock:
        if _langs is not None:
            return
        raw = json.loads(DATA_FILE.read_text(encoding="utf-8"))
        names = set(Language.__dataclass_fields__)
        langs = [Language(**{k: v for k, v in d.items() if k in names}) for d in raw["languages"]]
        by_code = {l.code: l for l in langs}
        alias: dict = {}
        # Least specific first so better matches overwrite: iso639-3, iso639-1, whisper, engine codes.
        for l in sorted(langs, key=lambda l: (l.popular == 0, l.popular), reverse=True):
            for key in (l.iso639_3, l.iso639_1, l.whisper_code, l.engines.get("nllb"), l.engines.get("omniasr")):
                if key:
                    alias[key.lower()] = l.code
        for k, v in MACRO_DEFAULT.items():
            if v in by_code:
                alias.setdefault(k, v)
        for l in langs:
            alias[l.code.lower()] = l.code
        _meta = raw.get("meta", {})
        _by_code.clear()
        _by_code.update(by_code)
        _alias.clear()
        _alias.update(alias)
        _langs = sorted(langs, key=lambda l: (l.popular == 0, l.popular, normalize(l.name_es)))


def meta() -> dict:
    _load()
    return dict(_meta)


def all() -> list:  # noqa: A001 (contract name)
    """Every language, ordered for display (ranked first, then by Spanish name)."""
    _load()
    return list(_langs)


def resolve(code: str) -> Optional[str]:
    """Canonical code for any code we understand ("es", "spa", "es-PE", "quy", "zho_Hans", "quy_Latn")."""
    _load()
    if not code:
        return None
    c = str(code).strip()
    if c in _by_code:
        return c
    low = c.lower().replace("-", "_")
    if low in _alias:
        return _alias[low]
    base = low.split("_")[0]
    return _alias.get(base)


def get(code: str) -> Optional[Language]:
    """Language for any accepted code, or None."""
    canon = resolve(code)
    return _by_code.get(canon) if canon else None


def ui_list(feature: str = "asr") -> list:
    """Languages usable for `feature` ("asr", "tts", "translate", "any", "all") as dicts for the kiosk."""
    if feature not in FEATURES:
        raise ValueError("feature must be one of %s" % (FEATURES,))
    out = []
    for l in all():
        if not l.has(feature):
            continue
        out.append({
            "code": l.code, "name": l.name_es, "name_es": l.name_es, "name_native": l.name_native,
            "name_en": l.name_en, "region": l.region, "popular": l.popular, "peru": l.peru,
            "asr": list(l.asr), "tts": list(l.tts), "translate": l.translate,
            "quality": dict(l.quality),
        })
    return out


def search(query: str, feature: str = "any", limit: int = 30) -> list:
    """Accent-insensitive search over native/Spanish/English names, aliases and codes.

    Ranking: exact name/code > name starts with query > word starts with query >
    substring; ties by popularity. "aimara", "Aimara", "aymara", "quechua cusco",
    "runasimi", "日本語", "ja" all work.
    """
    _load()
    q = normalize(query)
    if not q:
        return [l for l in all() if l.has(feature)][:limit]
    words = q.split()
    scored = []
    for l in _langs:
        if not l.has(feature):
            continue
        fields = [normalize(x) for x in (l.name_es, l.name_en, l.name_native)]
        aliases = [normalize(a) for a in l.aliases]
        codes = [x.lower() for x in (l.code, l.iso639_3, l.iso639_1, l.whisper_code) if x]
        hay = " ".join(fields + aliases)
        best = None
        if q in codes:
            best = 0
        elif q in fields or q in aliases:
            best = 1
        elif any(f.startswith(q) for f in fields):
            best = 2
        elif builtins.all(any(t.startswith(w) for t in re.split(r"[\s(),\-/]+", hay)) for w in words):
            best = 3
        elif builtins.all(w in hay for w in words):
            best = 4
        if best is not None:
            scored.append((best, l.popular == 0, l.popular, normalize(l.name_es), l))
    scored.sort(key=lambda t: t[:4])
    return [t[-1] for t in scored[:limit]]


def peru() -> list:
    """Peruvian languages (Spanish, Quechua varieties, Aymara, Jaqaru, Amazonian) in display order."""
    return [l for l in all() if l.peru]
